
name: Nightly

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nightly:
    concurrency:
      group: nightly
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven
    steps:
      - name: Set build information
        if: ${{ always() }}
        run: |
          echo "project_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "project_name=${{github.repository}}" >> $GITHUB_ENV
          echo "action_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
      - name: Set failure message
        if: ${{ failure() }}
        run: echo "zulip_message='The ${{env.project_name}} ${{env.project_branch}} branch has failed. See ${{env.action_url}}.'" >> $GITHUB_ENV  
      - name: Set success message
        if: ${{ success() }}
        run: echo "zulip_message='The ${{env.project_name}} ${{env.project_branch}} branch was successfully tested. See ${{env.action_url}}.'" >> $GITHUB_ENV  
      - name: Send a stream message
        if: ${{ always() }}
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ secrets.ZULIP_EMAIL }}
          organization-url: 'https://kie.zulipchat.com'
          to: 'optaplanner-dev'
          type: 'stream'
          topic: 'status of ${{env.project_name}} - ${{env.project_branch}}'
          content: ${{ env.zulip_message }}
