
name: Nightly

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  nightly:
    concurrency:
      group: nightly
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven
    steps:
      - name: Set failure message
        if: ${{ failure() }}
        run: echo "zulip_message='[TEST] The ${{github.repository}} ${GITHUB_REF#refs/heads/} branch has failed.'" >> $GITHUB_ENV  
      - name: Set success message
        if: ${{ success() }}
        run: echo "zulip_message='[TEST] The ${{github.repository}} ${GITHUB_REF#refs/heads/} branch was successfully tested.'" >> $GITHUB_ENV  
      - name: Send a stream message
        if: ${{ always() }}
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ secrets.ZULIP_EMAIL }}
          organization-url: 'https://kie.zulipchat.com'
          to: 'optaplanner-dev'
          type: 'stream'
          topic: "status of ${{github.repository}} - ${{GITHUB_REF#refs/heads/}}"
          content: ${{ env.zulip_message }}
